In [20]:
import tensorflow as tf 



In [21]:
mnist = tf.keras.datasets.mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()


### 8비트 회색조 이미지, 28*28px 크기. 총 데이터 7만개. 6:1 비율로 train_test_split 되어 있음.


In [22]:
X_train, X_test = X_train / 255.0, X_test / 255.0
# 딥러닝에서는 곱셈 연산이 많이 일어나므로 스케일링 해주기.

In [23]:
'''
모델 정의
입력층 설정
출력층 설정
은닉층 설정
모델 컴파일
예측
검증
'''

'\n모델 정의\n입력층 설정\n출력층 설정\n은닉층 설정\n모델 컴파일\n예측\n검증\n'

In [24]:
model = tf.keras.models.Sequential(
    [
        tf.keras.layers.Flatten(input_shape=(28,28)), # 입력층 -> 입력 데이터 쉐입 입력.
        tf.keras.layers.Dense(128, activation='relu'), # Dense = 데이터의 입력 레이어와 출력 레이어를 연결. 128개의 뉴런이 있는 완전 연결층을 추가, activation : 활성 함수.
        tf.keras.layers.Dropout(0.2),  # 모델이 학습할 때, 은닉층의 일부분을 랜덤하게 꺼 버리는 것.(교차 검증, 여기서는 20%를 랜덤하게 꺼 버림.) -> 딥러닝에서 과적합 막기 위해 사용.
        tf.keras.layers.Dense(10, activation='softmax') # 출력층 -> y의 클래스 개수 입력.
    ]
)

In [25]:
model.compile(
    optimizer = 'adam', # 손실 최적화 알고리즘
    loss = 'sparse_categorical_crossentropy', # 손실 함수 -> 오차 계산을 어떻게 할 것인가.
    metrics = ['accuracy'] # 평가 지표
)

In [26]:
X_train[0:1]

array([[[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.

In [46]:
predictions = model(X_train[0:1]) # 인풋 데이터 쉐입 맞추기 위해 한 가지만 넣음. 0번 이미지 예측값.

In [47]:
predictions.numpy() # 넘파이로 변환 : 보기 어려워서이다. 0~9 까지의 숫자 중 무엇일까 예측. (1일 확률이 제일 높다고 하므로 1일 확률이 가장 높다고 예측한 것..)

array([[9.6942107e-17, 2.7581282e-09, 7.3640823e-11, 1.6801328e-04,
        1.4952305e-27, 9.9983191e-01, 2.7902958e-19, 3.6993030e-13,
        3.2856956e-16, 1.2353622e-12]], dtype=float32)

In [41]:
y_train # 이 이미지가 무슨 숫자가 적혀 있는지 답이 적혀 있는 것. 0번 이미지는 5가 적힌 손글씨 이미지다.(틀림)

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [32]:
tf.nn.softmax(predictions).numpy() # 예측값이 맞을 확률. 각 값들은 합이 1이 됨. 역시 1일 확률이 가장 높음.

array([[0.09716973, 0.10871527, 0.09474649, 0.10136758, 0.09922414,
        0.09847651, 0.09863923, 0.09623731, 0.10759772, 0.09782599]],
      dtype=float32)

In [40]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True) # 손실값 계산 -> 모델의 예측과 실제 정답 간의 차이 계산
loss_fn(y_train[0:1], predictions).numpy()

2.4581213

### 우리가 머신러닝에서 했듯이 fit 가능.

In [36]:
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 845us/step - accuracy: 0.8603 - loss: 0.4772
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 853us/step - accuracy: 0.9569 - loss: 0.1437
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 845us/step - accuracy: 0.9691 - loss: 0.1048
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 830us/step - accuracy: 0.9723 - loss: 0.0868
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 825us/step - accuracy: 0.9795 - loss: 0.0685
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 842us/step - accuracy: 0.9800 - loss: 0.0612
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 840us/step - accuracy: 0.9825 - loss: 0.0542
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 840us/step - accuracy: 0.9847 - loss: 0.0469
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 843us/step - accuracy: 0.9860 - loss: 0.0425
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 842us/step - accuracy: 0.9864 - loss: 0.0409


In [37]:
model.evaluate(X_test, y_test) # [loss, accuracy] 순서다.

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 472us/step - accuracy: 0.9757 - loss: 0.0836


[0.0705016627907753, 0.9782999753952026]

In [38]:
model.predict(X_train[18:20]) # 예측값

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step


array([[3.3488357e-06, 5.8161721e-08, 2.6188857e-06, 1.2800841e-06,
        1.7545096e-06, 1.3283630e-02, 9.8626268e-01, 6.9041093e-08,
        4.4451645e-04, 5.5657843e-08],
       [4.0053545e-14, 1.8721125e-06, 1.7243862e-12, 5.4161272e-05,
        1.0423778e-05, 4.0027053e-06, 4.0780167e-14, 6.8788795e-05,
        6.5081792e-07, 9.9985993e-01]], dtype=float32)