In [9]:
import numpy as np

# 1차원 넘파이 배열 생성
array_1d = np.array([1, 2, 3])
print(array_1d)
print(type(array_1d))

# 리스트의 특징 : 자료형 구분이 없다
# 배열의 특징 : 자료형은 하나만 허용한다. 만약 다른 문자열이 있으면 통일해버린다.
array_1d = np.array([1, 2, "3", 4.1])
print(array_1d)

# 2차원 넘파이 배열 생성
array_2d = np.array([[1], [2], ["2"], [4.1]])
print(array_2d)

[1 2 3]
<class 'numpy.ndarray'>
['1' '2' '3' '4.1']
[['1']
 ['2']
 ['2']
 ['4.1']]


In [17]:
zero_array = np.zeros(10)  # 인자에 적은 숫자만큼 배열을 0으로 채움
print(zero_array)

# 행 5, 열 10
zero_array_2d = np.zeros((5, 10))
print(zero_array_2d)

# 9로 채워진 3*3 2차원 배열
nine_array_2d = np.full((3, 3), 9)
print(nine_array_2d)

# 랜덤값으로 채운 배열
random_array = np.random.random(10)
print(random_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[9 9 9]
 [9 9 9]
 [9 9 9]]
[0.39749132 0.55380033 0.78138647 0.69693513 0.54588058 0.27302083
 0.46649227 0.71306315 0.26757147 0.28891977]


In [23]:
# 배열의 연산
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print(array1 + array2)  # 각자 자리끼리 더한 값을 반환

array3 = np.array([7, 8])
# print(array1 + array3) # 두 배열의 길이가 달라서 오류 발생

print(array1 * array2)

[5 7 9]
[ 4 10 18]


In [28]:
array1_2d = np.array([[1, 2], [3, 4]])
array2_2d = np.array([[5, 6], [7, 8]])
# 사칙연산

print(array1_2d + array2_2d)
print(array1_2d - array2_2d)

print(array1_2d * array2_2d)
print(array1_2d / array2_2d)
# 각각의 자리끼리 연산

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [36]:
# 배열의 차원(행과 열)크기 shape
array_1d = np.zeros(12)
print(array_1d)
print(array_1d.shape)  # shape : 배열의 구조 확인

array_2d = np.zeros((3, 4))
print(array_2d)
print(array_2d.shape)  # shape : 배열의 구조 확인

array_2d = array_2d.reshape(
    (6, 2)
)  # reshape : 원소의 개수는 그대로 하고 구조를 바꿀 수 있다.
print(array_2d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(12,)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(3, 4)
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
